server:
  port: 8080

database: h2

spring:
  profiles:
    include: key
  jpa:
    show-sql: true
    format-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  output:
    ansi:
      enabled: always


logging:
  level:
    org:
      springframework:
        web: trace