server:
  port: '8081'

spring:
  profiles:
    include:
      - key
#      - real-db
  jpa:
    show-sql: true
    format-sql: true
    properties:
      hibernate:
        dialect:
          nodeValue: org.hibernate.dialect.MySQL57Dialect
          storage_engine: innodb

  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem://localhost/~/test;MODE=MYSQL

  session:
    store-type: jdbc
