server:
  port: 8080

spring:

  profiles:
    include:
      - key

  jpa:
    show-sql: true
    format-sql: true
    properties:
      hibernate:
        dialect:
          - org.hibernate.dialect.MySQL57Dialect
          - storage_engine: innodb

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem://localhost/~/test;MODE=MYSQL

  session:
    store-type: jdbc

  output:
    ansi:
      enabled: always