version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/dreamcalendar-test
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  AfterInstall:
    - location: scripts-test/stop.sh
      timeout: 60
      runas: ec2-user
  ApplicationStart:
    - location: scripts-test/start.sh
      timeout: 60
      runas: ec2-user